[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 10
restartPolicy = "on-failure"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"